application: travellog-nyuad
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: /
  static_files: index.html
  upload: index.html

- url: /log/.*
  static_files: index.html
  upload: index.html

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
